/**
 * Lighthouse Curaçao — database schema.
 *
 * Conventions that hold everywhere in this file:
 *   - Money is `integer` cents. There is no `numeric` money column anywhere.
 *   - Rates are `integer` basis points (700 = 7%).
 *   - Nights are `date` columns in `string` mode, so they arrive in JS as
 *     `YYYY-MM-DD` and never as a Date that a timezone can shift.
 *   - Stays are half-open ranges `[arrival, departure)`. Departure day is not
 *     slept in, so back-to-back bookings share a date without overlapping.
 *
 * The `stay` / `during` daterange columns are generated by Postgres from the
 * two date columns, so they cannot drift out of sync with them. The GiST
 * exclusion constraint that makes double-booking impossible lives in
 * `drizzle/0001_booking_exclusion.sql` — Drizzle has no DSL for EXCLUDE.
 */

import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  customType,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

/**
 * Postgres `daterange`. Always generated, never written directly, so the TS
 * type is only ever read back as its text form (`[2026-12-20,2026-12-27)`).
 */
const daterange = customType<{ data: string; driverData: string }>({
  dataType: () => "daterange",
});

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const bookingStatus = pgEnum("booking_status", [
  /** Dates are held while the guest pays. Blocks the calendar. */
  "pending",
  /** Paid (deposit or in full). Blocks the calendar, appears in the iCal feed. */
  "confirmed",
  /** Released. Deliberately excluded from the exclusion constraint. */
  "cancelled",
  /** Hold ran out before payment. Also released. */
  "expired",
]);

export const bookingSource = pgEnum("booking_source", [
  "direct",
  "manual",
  "airbnb",
  "booking_com",
]);

export const paymentPlan = pgEnum("payment_plan", ["deposit", "full"]);

export const paymentProvider = pgEnum("payment_provider", [
  "mollie",
  "stripe",
  /** Bank transfer or cash, registered by hand in /admin. */
  "manual",
  /** Dev/E2E only; the FakeProvider refuses to construct in production. */
  "fake",
]);

export const paymentKind = pgEnum("payment_kind", [
  "deposit",
  "balance",
  "full",
  "refund",
]);

export const paymentStatus = pgEnum("payment_status", [
  "open",
  "pending",
  "paid",
  "failed",
  "expired",
  "cancelled",
  "refunded",
]);

export const icalDirection = pgEnum("ical_direction", ["import", "export"]);

export const locale = pgEnum("locale", ["nl", "en", "pap"]);

// ---------------------------------------------------------------------------
// properties
// ---------------------------------------------------------------------------

export const properties = pgTable(
  "properties",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    slug: varchar("slug", { length: 64 }).notNull(),
    name: text("name").notNull(),

    /** IANA zone. Everything date-shaped is interpreted here, not in UTC. */
    timezone: text("timezone").notNull().default("America/Curacao"),
    /** ISO 4217. Curaçao prices in USD; the guilder is pegged to it. */
    currency: varchar("currency", { length: 3 }).notNull().default("USD"),

    maxGuests: integer("max_guests").notNull(),
    bedrooms: integer("bedrooms").notNull(),
    bathrooms: integer("bathrooms").notNull(),

    cleaningFeeCents: integer("cleaning_fee_cents").notNull().default(0),
    /** 7% Curaçao turnover tax = 700 bps. */
    taxRateBps: integer("tax_rate_bps").notNull().default(700),
    /** Whether the turnover tax also applies to the cleaning fee. */
    taxOnCleaningFee: boolean("tax_on_cleaning_fee").notNull().default(true),

    /** Share of the total taken up front. 30% = 3000 bps. */
    depositBps: integer("deposit_bps").notNull().default(3000),
    /** Remaining balance falls due this many days before arrival. */
    balanceDueDays: integer("balance_due_days").notNull().default(35),
    /** Below this many days to arrival, only pay-in-full is offered. */
    payInFullWithinDays: integer("pay_in_full_within_days").notNull().default(35),
    /** How long a pending booking holds the dates while payment is in flight. */
    holdMinutes: integer("hold_minutes").notNull().default(30),

    /** Guard rails; a stay outside these is refused before it reaches pricing. */
    minNightsFloor: integer("min_nights_floor").notNull().default(1),
    maxNights: integer("max_nights").notNull().default(90),
    /** Earliest arrival, counted in days from today. 0 = same-day allowed. */
    minAdvanceDays: integer("min_advance_days").notNull().default(0),
    /** How far ahead the calendar is open for booking. */
    maxAdvanceDays: integer("max_advance_days").notNull().default(540),

    checkInTime: varchar("check_in_time", { length: 5 }).notNull().default("15:00"),
    checkOutTime: varchar("check_out_time", { length: 5 }).notNull().default("11:00"),

    addressLine: text("address_line").notNull(),
    city: text("city").notNull(),
    country: varchar("country", { length: 2 }).notNull().default("CW"),
    latitude: text("latitude"),
    longitude: text("longitude"),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("properties_slug_key").on(t.slug),
    check("properties_max_guests_positive", sql`${t.maxGuests} > 0`),
    check("properties_cleaning_fee_non_negative", sql`${t.cleaningFeeCents} >= 0`),
    check("properties_tax_rate_sane", sql`${t.taxRateBps} between 0 and 10000`),
    check("properties_deposit_sane", sql`${t.depositBps} between 0 and 10000`),
    check("properties_nights_sane", sql`${t.maxNights} >= ${t.minNightsFloor}`),
  ],
);

// ---------------------------------------------------------------------------
// seasons
// ---------------------------------------------------------------------------

/**
 * A dated price band. Ranges are inclusive on both ends because that is how an
 * owner reads a calendar ("high season runs 15 Dec through 15 Apr").
 *
 * Ranges are allowed to overlap: `priority` decides which one wins for a given
 * night, so a one-off Christmas-week rate can sit on top of high season without
 * anyone having to cut the underlying band into pieces.
 */
export const seasons = pgTable(
  "seasons",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    startDate: date("start_date", { mode: "string" }).notNull(),
    endDate: date("end_date", { mode: "string" }).notNull(),
    nightlyPriceCents: integer("nightly_price_cents").notNull(),
    minNights: integer("min_nights").notNull().default(1),
    /** Higher wins where bands overlap. */
    priority: integer("priority").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("seasons_property_dates_idx").on(t.propertyId, t.startDate, t.endDate),
    check("seasons_range_ordered", sql`${t.endDate} >= ${t.startDate}`),
    check("seasons_price_positive", sql`${t.nightlyPriceCents} > 0`),
    check("seasons_min_nights_positive", sql`${t.minNights} >= 1`),
  ],
);

// ---------------------------------------------------------------------------
// blocked_dates
// ---------------------------------------------------------------------------

/**
 * Nights that are unavailable without being a booking: owner stays,
 * maintenance, and everything imported from Airbnb or Booking.com.
 *
 * `source` is the feed label for imports and `owner` for blocks made in
 * /admin, so an imported block is never mistaken for one of your own — and a
 * re-run of the importer can delete exactly its own rows and nothing else.
 * `externalUid` is the feed's VEVENT UID, which makes that sync idempotent.
 */
export const blockedDates = pgTable(
  "blocked_dates",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    /** First blocked night. */
    startDate: date("start_date", { mode: "string" }).notNull(),
    /** Exclusive: the first night that is free again. */
    endDate: date("end_date", { mode: "string" }).notNull(),
    during: daterange("during").generatedAlwaysAs(
      sql`daterange(start_date, end_date, '[)')`,
    ),
    /** `owner`, or the ical_feeds label for an imported block. */
    source: text("source").notNull().default("owner"),
    externalUid: text("external_uid"),
    reason: text("reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("blocked_dates_property_idx").on(t.propertyId, t.startDate),
    uniqueIndex("blocked_dates_source_uid_key")
      .on(t.propertyId, t.source, t.externalUid)
      .where(sql`external_uid is not null`),
    check("blocked_dates_range_ordered", sql`${t.endDate} > ${t.startDate}`),
  ],
);

// ---------------------------------------------------------------------------
// guests
// ---------------------------------------------------------------------------

export const guests = pgTable(
  "guests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    email: text("email").notNull(),
    firstName: text("first_name").notNull(),
    lastName: text("last_name").notNull(),
    phone: text("phone"),
    /** ISO 3166-1 alpha-2 of the guest's home country, for the tax return. */
    country: varchar("country", { length: 2 }),
    addressLine: text("address_line"),
    postalCode: text("postal_code"),
    city: text("city"),
    locale: locale("locale").notNull().default("nl"),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // A plain column index so ON CONFLICT can target it; the CHECK below
    // keeps the column lowercase, so it is still case-insensitively unique.
    uniqueIndex("guests_email_key").on(t.email),
    check("guests_email_shape", sql`position('@' in ${t.email}) > 1`),
    check("guests_email_lowercase", sql`${t.email} = lower(${t.email})`),
  ],
);

// ---------------------------------------------------------------------------
// bookings
// ---------------------------------------------------------------------------

/**
 * The money columns are a frozen copy of the quote as it stood when the guest
 * agreed to it. Editing a season later must never restate an existing booking,
 * so nothing here is recomputed from `seasons` after the fact. `breakdown`
 * keeps the full per-night quote as JSON for the confirmation e-mail and for
 * any later argument about what was charged.
 */
export const bookings = pgTable(
  "bookings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** Human-facing code, e.g. LH-2026-0042. Quoted in every e-mail. */
    reference: varchar("reference", { length: 24 }).notNull(),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "restrict" }),
    guestId: uuid("guest_id")
      .notNull()
      .references(() => guests.id, { onDelete: "restrict" }),

    status: bookingStatus("status").notNull().default("pending"),
    source: bookingSource("source").notNull().default("direct"),

    arrivalDate: date("arrival_date", { mode: "string" }).notNull(),
    /** Exclusive: the guest does not sleep here on the departure date. */
    departureDate: date("departure_date", { mode: "string" }).notNull(),
    stay: daterange("stay").generatedAlwaysAs(
      sql`daterange(arrival_date, departure_date, '[)')`,
    ),
    nights: integer("nights").notNull(),
    guests: integer("guests").notNull(),

    currency: varchar("currency", { length: 3 }).notNull(),
    accommodationCents: integer("accommodation_cents").notNull(),
    cleaningFeeCents: integer("cleaning_fee_cents").notNull(),
    taxCents: integer("tax_cents").notNull(),
    taxRateBps: integer("tax_rate_bps").notNull(),
    totalCents: integer("total_cents").notNull(),
    depositCents: integer("deposit_cents").notNull(),
    balanceCents: integer("balance_cents").notNull(),
    balanceDueDate: date("balance_due_date", { mode: "string" }),
    paymentPlan: paymentPlan("payment_plan").notNull(),
    /** The quote, exactly as shown to the guest. */
    breakdown: jsonb("breakdown").notNull(),

    locale: locale("locale").notNull().default("nl"),
    guestMessage: text("guest_message"),
    internalNotes: text("internal_notes"),

    /** When a `pending` hold lapses. Null once confirmed. */
    holdExpiresAt: timestamp("hold_expires_at", { withTimezone: true }),
    confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    cancellationReason: text("cancellation_reason"),

    /** Set once each so a retry or a replayed webhook cannot send twice. */
    confirmationEmailSentAt: timestamp("confirmation_email_sent_at", { withTimezone: true }),
    balanceReminderSentAt: timestamp("balance_reminder_sent_at", { withTimezone: true }),
    arrivalEmailSentAt: timestamp("arrival_email_sent_at", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("bookings_reference_key").on(t.reference),
    index("bookings_property_arrival_idx").on(t.propertyId, t.arrivalDate),
    index("bookings_status_idx").on(t.status),
    check("bookings_range_ordered", sql`${t.departureDate} > ${t.arrivalDate}`),
    check(
      "bookings_nights_match_range",
      sql`${t.nights} = ${t.departureDate} - ${t.arrivalDate}`,
    ),
    check("bookings_guests_positive", sql`${t.guests} > 0`),
    check("bookings_amounts_non_negative", sql`
      ${t.accommodationCents} >= 0 and ${t.cleaningFeeCents} >= 0
      and ${t.taxCents} >= 0 and ${t.totalCents} >= 0
      and ${t.depositCents} >= 0 and ${t.balanceCents} >= 0
    `),
    check(
      "bookings_total_adds_up",
      sql`${t.totalCents} = ${t.accommodationCents} + ${t.cleaningFeeCents} + ${t.taxCents}`,
    ),
    check(
      "bookings_deposit_adds_up",
      sql`${t.totalCents} = ${t.depositCents} + ${t.balanceCents}`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// payments
// ---------------------------------------------------------------------------

/**
 * One row per attempt at moving money, including the failed ones — a guest who
 * abandons iDEAL and then pays by card leaves two rows, and only the second is
 * `paid`.
 *
 * `providerPaymentId` is unique so a webhook that arrives twice (they do)
 * updates a row rather than inserting one.
 */
export const payments = pgTable(
  "payments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    bookingId: uuid("booking_id")
      .notNull()
      .references(() => bookings.id, { onDelete: "restrict" }),
    provider: paymentProvider("provider").notNull(),
    /** Mollie `tr_...` / Stripe `pi_...`. Null only for manual registrations. */
    providerPaymentId: text("provider_payment_id"),
    kind: paymentKind("kind").notNull(),
    status: paymentStatus("status").notNull().default("open"),
    amountCents: integer("amount_cents").notNull(),
    currency: varchar("currency", { length: 3 }).notNull(),
    /** `ideal`, `creditcard`, `bancontact`, `banktransfer`, … */
    method: text("method"),
    description: text("description"),
    checkoutUrl: text("checkout_url"),
    paidAt: timestamp("paid_at", { withTimezone: true }),
    failedAt: timestamp("failed_at", { withTimezone: true }),
    refundedCents: integer("refunded_cents").notNull().default(0),
    /** Last webhook body, verbatim, for reconciliation and disputes. */
    providerPayload: jsonb("provider_payload"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("payments_provider_payment_id_key")
      .on(t.provider, t.providerPaymentId)
      .where(sql`provider_payment_id is not null`),
    index("payments_booking_idx").on(t.bookingId),
    check("payments_amount_positive", sql`${t.amountCents} > 0`),
    check("payments_refund_within_amount", sql`${t.refundedCents} between 0 and ${t.amountCents}`),
  ],
);

// ---------------------------------------------------------------------------
// ical_feeds
// ---------------------------------------------------------------------------

export const icalFeeds = pgTable(
  "ical_feeds",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    /** Also the `source` written onto imported blocked_dates rows. */
    label: text("label").notNull(),
    direction: icalDirection("direction").notNull().default("import"),
    url: text("url"),
    active: boolean("active").notNull().default(true),
    lastSyncAt: timestamp("last_sync_at", { withTimezone: true }),
    lastSyncStatus: text("last_sync_status"),
    lastSyncError: text("last_sync_error"),
    importedCount: integer("imported_count"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("ical_feeds_property_label_key").on(t.propertyId, t.label),
    check("ical_feeds_import_needs_url", sql`${t.direction} <> 'import' or ${t.url} is not null`),
  ],
);

// ---------------------------------------------------------------------------
// audit_log
// ---------------------------------------------------------------------------

/**
 * Append-only. Every admin mutation and every webhook that changes money or
 * availability writes here, so a year later you can still answer "who
 * cancelled that and when".
 */
export const auditLog = pgTable(
  "audit_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** Admin e-mail, `system` for cron, or the provider name for webhooks. */
    actor: text("actor").notNull(),
    action: text("action").notNull(),
    entity: text("entity").notNull(),
    entityId: uuid("entity_id"),
    before: jsonb("before"),
    after: jsonb("after"),
    ip: text("ip"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("audit_log_entity_idx").on(t.entity, t.entityId),
    index("audit_log_created_at_idx").on(t.createdAt),
  ],
);

// ---------------------------------------------------------------------------
// rate_limits
// ---------------------------------------------------------------------------

/**
 * Fixed-window rate limiting in Postgres, so it holds across serverless
 * instances without adding Redis to the stack. One row per (key, window);
 * `count` is bumped with an atomic upsert. A cron sweeps expired windows.
 */
export const rateLimits = pgTable(
  "rate_limits",
  {
    /** e.g. `quote:203.0.113.7` */
    key: text("key").notNull(),
    windowStart: timestamp("window_start", { withTimezone: true }).notNull(),
    count: integer("count").notNull().default(1),
  },
  (t) => [
    primaryKey({ columns: [t.key, t.windowStart] }),
    index("rate_limits_window_idx").on(t.windowStart),
  ],
);

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

export type Property = typeof properties.$inferSelect;
export type NewProperty = typeof properties.$inferInsert;
export type Season = typeof seasons.$inferSelect;
export type NewSeason = typeof seasons.$inferInsert;
export type BlockedDate = typeof blockedDates.$inferSelect;
export type NewBlockedDate = typeof blockedDates.$inferInsert;
export type Guest = typeof guests.$inferSelect;
export type NewGuest = typeof guests.$inferInsert;
export type Booking = typeof bookings.$inferSelect;
export type NewBooking = typeof bookings.$inferInsert;
export type Payment = typeof payments.$inferSelect;
export type NewPayment = typeof payments.$inferInsert;
export type IcalFeed = typeof icalFeeds.$inferSelect;
export type NewIcalFeed = typeof icalFeeds.$inferInsert;
export type AuditLogEntry = typeof auditLog.$inferSelect;
export type NewAuditLogEntry = typeof auditLog.$inferInsert;
